version: '3'

services:

  fitapp:
    build: .
    depends_on:
      - postgres
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - app.env

  postgres:
    image: postgres:12.3
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - app.env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.15-alpine
    container_name: redis
    hostname: redis


  worker:
    build:
      context: .
    container_name: celery
    hostname: worker
    entrypoint: celery
    command: -A core.celery.app worker --loglevel=info
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis

volumes:
  local_postgres_data: {}