# Generated by Django 5.0.4 on 2024-04-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainer',
            table='trainers',
        ),
    ]
