# Generated by Django 5.0.4 on 2024-04-07 10:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('trainer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 4, 7))),
                ('start_time', models.TimeField(default=datetime.time(10, 27, 37, 164043))),
                ('end_time', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gym.gym')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trainer.trainer')),
            ],
            options={
                'db_table': 'appointments',
                'unique_together': {('client', 'gym', 'date', 'start_time', 'end_time'), ('client', 'trainer', 'gym', 'date', 'start_time', 'end_time'), ('trainer', 'gym', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
