# Generated by Django 5.0.4 on 2024-04-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('schedule', '0002_initial'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleunit',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleunit',
            unique_together={('trainer', 'gym', 'week_day', 'start_time', 'end_time')},
        ),
    ]
