# Generated by Django 5.0.4 on 2024-04-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduleunit_week_day_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scheduleunit',
            table='schedule_units',
        ),
    ]
