# Generated by Django 5.0.4 on 2024-04-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gym',
            table='gyms',
        ),
    ]
